/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReentrantWithdrawReceiverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attackWithdraw"
      | "createPost"
      | "reentryAttempted"
      | "reentrySucceeded"
      | "setTargetPostId"
      | "targetPostId"
      | "tipPost"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attackWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPost",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "reentryAttempted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reentrySucceeded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetPostId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "targetPostId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tipPost", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "attackWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reentryAttempted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentrySucceeded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetPostId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetPostId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tipPost", data: BytesLike): Result;
}

export interface ReentrantWithdrawReceiver extends BaseContract {
  connect(runner?: ContractRunner | null): ReentrantWithdrawReceiver;
  waitForDeployment(): Promise<this>;

  interface: ReentrantWithdrawReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attackWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  createPost: TypedContractMethod<
    [imageUrl: string, caption: string],
    [void],
    "nonpayable"
  >;

  reentryAttempted: TypedContractMethod<[], [boolean], "view">;

  reentrySucceeded: TypedContractMethod<[], [boolean], "view">;

  setTargetPostId: TypedContractMethod<
    [postId: BigNumberish],
    [void],
    "nonpayable"
  >;

  targetPostId: TypedContractMethod<[], [bigint], "view">;

  tipPost: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attackWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<
    [imageUrl: string, caption: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reentryAttempted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "reentrySucceeded"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setTargetPostId"
  ): TypedContractMethod<[postId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "targetPostId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tipPost"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
