/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RejectEtherReceiverInterface extends Interface {
  getFunction(
    nameOrSignature: "createPost" | "tipPost" | "withdrawEscrowedTips"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createPost",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "tipPost", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawEscrowedTips",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tipPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEscrowedTips",
    data: BytesLike
  ): Result;
}

export interface RejectEtherReceiver extends BaseContract {
  connect(runner?: ContractRunner | null): RejectEtherReceiver;
  waitForDeployment(): Promise<this>;

  interface: RejectEtherReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPost: TypedContractMethod<
    [imageUrl: string, caption: string],
    [void],
    "nonpayable"
  >;

  tipPost: TypedContractMethod<[], [string], "view">;

  withdrawEscrowedTips: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<
    [imageUrl: string, caption: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tipPost"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawEscrowedTips"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
